---

- name: playbook for testing tenants
  hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: Add a new tenant
    aci_tenant:
      tenant: TN_Freita
      description: From Ansible
      state: present
      validate_certs: false
