---

- name: Creating Tenants
  hosts: apic
  connection: local
  gather_facts: no
  remote_Src: yes
  vars_files:
    - https://raw.githubusercontent.com/dev-rfreitas/aula01/main/external_vars.yml
    
  tasks:
  - name: Add a new tenant
    aci_tenant:
      hostname: "{{ inventory_hostname }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      tenant: "{{ tenant }}"
      description: "{{ description }}"
      state: present
      validate_certs: false
