---

- name: Creating Tenants
  hosts: apic
  connection: local
  gather_facts: no
  vars_files:
    - /home/semaphore/external_vars.yml

  tasks:
  - name: Add a new tenant
    aci_tenant:
      hostname: "{{ inventory_hostname }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      tenant: "{{ tenant }}"
      description: "{{ description }}"
      state: present
      validate_certs: false
