---

- name: Application Profile
  hosts: apic
  connection: local
  gather_facts: no
  vars_files:
    - /home/semaphore/external_vars.yml

  tasks:
  - name: create app network profile
    aci_ap:
      ap: "{{ ap }}"
      tenant: "{{ tenant }}"
      state: present
      hostname: "{{ inventory_hostname }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      validate_certs: false

  - name: Creating EPG
    aci_epg:
      epg: "{{ epg }}"
      bd: "{{ bd.name }}"
      ap: "{{ ap }}"
      tenant: "{{ tenant }}"
      state: present
      hostname: "{{ inventory_hostname }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      validate_certs: false
