---

- name: playbook for creating vRF
  hosts: apic
  connection: local
  gather_facts: no
  vars_files:
    - https://github.com/dev-rfreitas/aula01/blob/main/external_vars.yml

  tasks:
  - name: Ensure vRF for tenant exists
    aci_vrf:
      vrf: "{{ vrf.name }}"
      description: "{{ vrf.description }}"
      tenant: "{{ vrf.tenant }}"
      state: present
      host: "{{ inventory_hostname }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      validate_certs: false

  - name: Associating vRF to Bridge domain
    aci_bd:
      bd: "{{ bd.name }}"
      vrf: "{{ bd.vrf }}"
      tenant: "{{ bd.tenant }}"
      state: present
      host: "{{ inventory_hostname }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      validate_certs: false
